<a href="https://colab.research.google.com/github/shivanshu1512/Movie_IMDB/blob/main/assignment_lecture4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [ ]:
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [ ]:
# Problem 1

# Apply all the preprocessing techniques that you think are necessary
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv(
    "IMDB Dataset.csv",
    engine="python",
    on_bad_lines="skip"
)

print(df.shape)
df.head()

(35631, 2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35631 entries, 0 to 35630
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     35631 non-null  object
 1   sentiment  35631 non-null  object
dtypes: object(2)
memory usage: 556.9+ KB

In [ ]:
df.info

<bound method DataFrame.info of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
35626  Unfortunately there was not a 0 for a rating o...  negative
35627  This is a failure so complete as to make me an...  negative
35628  I had to compare two versions of Hamlet for my...  negative
35629  I was still living with my parents when they a...  positive
35630  Castle of Blood is a good example of the quali...  positive

[35631 rows x 2 columns]>

In [ ]:
print(df.isnull().sum())

review       0
sentiment    0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.shape

(35421, 2)

In [ ]:
df['sentiment'] = df['sentiment'].map({
    'positive': 1,
    'negative': 0
})

/tmp/ipykernel_465/4206657310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = df['sentiment'].map({

In [ ]:
df.head(6)

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1
5  Probably my all-time favorite movie, a story o...          1

In [ ]:
# Problem 2

# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python

In [ ]:
df['clean_review']

KeyError: 'clean_review'

In [ ]:
# Problem 3

# Apply One Hot Encoding

In [ ]:
# Problem 4

# Apply bag words and find the vocabulary also find the times each word has occured

In [ ]:
# Problem 5

# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary

In [ ]:
# Problem 6

# Apply tf-idf and find out the idf scores of words, also find out the vocabulary.